# Generated by Django 5.0.1 on 2024-09-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date accept'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date interview'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('I', 'Interview'), ('O', 'Offer'), ('R', 'Rejection')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.TextField(),
        ),
    ]
